# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 64d4603c0eba4bc8656c8c06664d5cf6636bf593cdb7077456fbe4824d45995153e523931965d71c20a7de206572459115e8d6642e88b5c423382ad3a9b341e2
  runa_api_base: http://localhost:3000/

test:
  secret_key_base: bc717d97092b76badc15578603ee80280e05b267ee6b59fba3c5b4b52989096d74cb9e3703f94837a6dc8b3352929b43ad08724c031fd814036eb34da3ba6d51

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  runa_api_base: http://localhost:3000/